### PR TITLE
Use latest mdns, fixes build on Slackware

### PR DESCRIPTION
**Pull request by rcombs**

### CODE REVIEW

**Comment by benvanik** [comment]
Awesome - this means I can remove my fork of mdns, too. Thanks for doing this!

**Comment by rcombs** [comment]
No big deal, since the latest version works on Slackware I just had to change the link to a version number in the JSON.

**Comment by rcombs** [comment]
Could you post 0.0.3 to npm?

**Comment by benvanik** [comment]
Yep! I'll do it tonight when I get on my machine at home

## 

Ben Vanik
http://www.noxa.org

**Pull request merged**
